from typing import Protocol


class ConversationRecord(Protocol):
    id: str
    title: str


class ConversationRepository(Protocol):
    async def create(self, title: str) -> ConversationRecord: ...
    async def get(self, conversation_id: str) -> ConversationRecord | None: ...
    async def list_all(self) -> list[ConversationRecord]: ...
    async def delete(self, conversation_id: str) -> None: ...


class SessionRepository(Protocol):
    async def get_request_count(self, session_id: str) -> int: ...
    async def increment(self, session_id: str) -> int: ...
